### ISSUE TITLE
Error after authorization

### ISSUE THREAD

**Issue by fluorek** [DAMcraft/MeteorServerSeeker#23]
[20:29:16] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Ticking screen
	at net.minecraft.class_437.method_25412(class_437.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1925) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[fabric-loader-0.14.24-1.20.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "de.damcraft.serverseeker.ServerSeekerSystem.get().discordAvatarUrl" is null
	at de.damcraft.serverseeker.gui.ServerSeekerScreen.initWidgets(ServerSeekerScreen.java:45) ~[server-seeker-4.0.0.jar:?]
	at meteordevelopment.meteorclient.gui.WidgetScreen.reload(WidgetScreen.java:109) ~[meteor-client-0.5.5-1977.jar:?]
	at de.damcraft.serverseeker.gui.ServerSeekerScreen.method_25393(ServerSeekerScreen.java:120) ~[server-seeker-4.0.0.jar:?]
	at net.minecraft.class_310.method_1572(class_310.java:1925) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	... 7 more
[20:29:16] [Thread-6/INFO]: Saving

**Comment by DAMcraft** [comment]
Could you see if this still happens when using the newest dev-build?
https://github.com/DAMcraft/MeteorServerSeeker/releases/download/latest/server-seeker-4.0.0.jar

**Comment by DAMcraft** [comment]
Will close for now, if the issue still occures, re-open the ticket

**Comment by FurnyGo** [comment]
![image](https://github.com/DAMcraft/MeteorServerSeeker/assets/68079109/c031094e-1ed2-476d-8903-9c6949e6c775)
If you have this error try to enable http in config tab in meteor

**Comment by DAMcraft** [comment]
@FurnyGo  This was a bug in an older version of MSS and has now been fixed lol
